#Utilizar la imagen oficial de Node.js
FROM node:16.17

#Establecer el directorio de trabajo
WORKDIR /app

#Copiar el resto del código
COPY . .

#Instalar las dependencias
RUN npm install

#Generar el build de Angular
RUN npm run build

#Iniciar la aplicación
CMD ["npm", "start"]